#!/bin/bash

DATE=`date`

mkdir -p openbox_config
mkdir -p tint2_config
mkdir -p tilda_config

cp -R ~/.config/openbox/ openbox_config
cp ~/.config/tint2/tint2rc tint2_config/tint2rc
cp -R ~/.tilda/ tilda_config
cp ~/.bashrc .bashrc
cp ~/.bash_logout .bash_logout
cp ~/.xinitrc .xinitrc

git add .
git commit -am "configs: $DATE"
git remote add origin git@github.com:2kgit/arch-config.git
git push -u origin master
